# Generated by Django 5.2.13 on 2026-04-29 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('CREATED', 'Создана'), ('ACCEPTED', 'Принята складом'), ('REJECTED', 'Отклонена')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия складом')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество единиц')),
                ('price_per_unit', models.PositiveIntegerField(verbose_name='Цена за единицу в копейках')),
            ],
            options={
                'verbose_name': 'Позиция накладной',
                'verbose_name_plural': 'Позиции накладных',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('ON_MODERATION', 'На модерации'), ('MODERATED', 'Опубликован'), ('BLOCKED', 'Заблокирован')], default='CREATED', max_length=20, verbose_name='Статус модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название характеристики')),
                ('value', models.CharField(max_length=500, verbose_name='Значение характеристики')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на изображение')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название варианта (артикул/модификация)')),
                ('price', models.PositiveIntegerField(verbose_name='Цена в копейках')),
                ('active_quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
            },
        ),
        migrations.CreateModel(
            name='SKUCharacteristic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название характеристики')),
                ('value', models.CharField(max_length=500, verbose_name='Значение характеристики')),
            ],
            options={
                'verbose_name': 'Характеристика SKU',
                'verbose_name_plural': 'Характеристики SKU',
            },
        ),
    ]
