# Generated by Django 5.2.13 on 2026-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_created_at_category_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='article',
            field=models.CharField(blank=True, max_length=255, verbose_name='Артикул'),
        ),
    ]
