# Generated by Django 5.2.13 on 2026-05-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sku_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='active_quantity',
            new_name='stock_quantity',
        ),
    ]
