# Generated by Django 5.2.13 on 2026-05-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_active_quantity_sku_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.CharField(max_length=500, verbose_name='Ссылка на изображение'),
        ),
    ]
