# Generated by Django 5.2.13 on 2026-05-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_description_alter_productimage_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'ordering'), name='unique_product_ordering'),
        ),
    ]
