# Generated by Django 5.2.13 on 2026-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Себестоимость в копейках'),
        ),
        migrations.AddField(
            model_name='sku',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='sku',
            name='reserved_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Остаток на складе'),
        ),
    ]
