# Generated by Django 5.2.13 on 2026-05-18 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sku_cost_price_sku_discount_sku_reserved_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500, verbose_name='Ссылка на изображение')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Изображение SKU',
                'verbose_name_plural': 'Изображения SKU',
                'ordering': ['ordering'],
                'constraints': [models.UniqueConstraint(fields=('sku', 'ordering'), name='unique_sku_ordering')],
            },
        ),
    ]
