# Generated by Django 5.2.13 on 2026-05-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_skuimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('ON_MODERATION', 'На модерации'), ('MODERATED', 'Опубликован'), ('BLOCKED', 'Заблокирован'), ('HARD_BLOCKED', 'Жестко заблокирован')], default='CREATED', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
