# Generated by Django 5.2.13 on 2026-05-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Себестоимость в копейках'),
        ),
    ]
