# Generated by Django 5.2.13 on 2026-05-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_moderator_comment_blockingreason_fieldreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockingreason',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_reason', to='app.product'),
        ),
    ]
