# Generated by Django 5.2.13 on 2026-05-29 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('event_type', models.CharField(choices=[('MODERATED', 'MODERATED'), ('BLOCKED', 'BLOCKED')], max_length=9)),
                ('moderator_id', models.UUIDField()),
                ('moderator_comment', models.TextField()),
                ('hard_block', models.BooleanField(blank=True, default=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_events', to='app.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Moderation',
        ),
    ]
