# Generated by Django 5.2.13 on 2026-05-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_moderationevent_delete_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
