# Generated by Django 5.2.13 on 2026-06-08 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockingreason',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='blocking_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.blockingreason', verbose_name='Причина блокировки'),
        ),
    ]
