# Generated by Django 5.2.13 on 2026-06-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_blockingreason_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationevent',
            name='occurred_at',
            field=models.DateTimeField(),
        ),
    ]
