# Generated by Django 5.2.15 on 2026-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_moderationevent_occurred_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationevent',
            name='moderator_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
